#!/bin/sh
# -*- sh -*-

: <<=cut

=head1 NAME

phpfpm_average - Munin plugin to monitor the average process size of PHP-FPM on the machine.

=head1 CONFIGURATION

You might need to specify connection parameters in the plugin
configuration to override the defaults. These are the defaults:

  [phpfpm_*]
    env.phpbin php-fpm
    env.phppool www

=head1 PARAMETERS:

 config (required)
 autoconf (optional - used by munin-config)

=over

=head1 LICENSE

Copyright TJ Stein 2010 http://constantshift.com

=head1 MAGICK MARKERS

  #%# family=manual
  #%# capabilities=autoconf

=cut


PHP_BIN=${phpbin-"php-fpm"}
# Get the list of all pools if non is specified in the config file
PHP_POOLS=${phppool-"$(ps -axo cmd | grep "php-fpm: pool" | grep -v grep | sort | uniq | cut -d" " -f 3)"}

if [ "$1" = "autoconf" ]; then
echo yes
exit 0
fi

if [ "$1" = "config" ]; then
echo 'graph_title PHP-FPM Average Process Size'
echo 'graph_args --base 1024 -l 0 '
echo 'graph_category PHP'
echo 'graph_info This graph shows the average process size for PHP-FPM'
for p in $PHP_POOLS; do
    echo "graph_vlabel PHP-FPM Average Process Size $p"
    echo "php_average_$p.label PHP-FPM Average Process Size: $p"
    echo "php_average_$p.draw LINE2"
    echo "php_average_$p.info The average process size for PHP-FPM for pool '$p'."
done
exit 0
fi

for p in $PHP_POOLS; do
    echo -n "php_average_$p.value "
    tmpfile=/dev/shm/$$
    ps awwwux | grep "${PHP_BIN}: pool $p" | grep -v grep | grep -v master > $tmpfile
    test -s $tmpfile && awk '{total_mem = $6 * 1024 + total_mem; total_proc++} END{printf("%d\n", total_mem / total_proc)}' $tmpfile || echo N
    rm -f $tmpfile
done
