#!/bin/sh
# -*- sh -*-

: <<=cut

=head1 NAME

phpfpm_connections - Munin plugin for monitoring PHP-FPM memory usage.

=head1 CONFIGURATION

You might need to specify connection parameters in the plugin
configuration to override the defaults. These are the defaults:

  [phpfpm_*]
    env.phpbin php-fpm
    env.phppool www

=head1 PARAMETERS:

 config (required)
 autoconf (optional - used by munin-config)

=over

=head1 LICENSE

Copyright TJ Stein 2010 http://constantshift.com

=head1 MAGICK MARKERS

  #%# family=auto
  #%# capabilities=autoconf

=cut

PHP_BIN=${phpbin-"php-fpm"}
# Get the list of all pools if non is specified in the config file
PHP_POOLS=${phppool-"$(ps -axo cmd | grep "php-fpm: pool" | grep -v grep | sort | uniq | cut -d" " -f 3)"}

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title PHP-FPM Memory Usage'
    echo 'graph_args --base 1024 -l 0 '
    echo 'graph_category PHP'
    echo 'graph_info This graph shows the memory usage of PHP-FPM pools in the system.'
    for p in $PHP_POOLS; do
	echo "graph_vlabel PHP-FPM RAM $p"
	echo "php_ram_$p.label PHP-FPM ram: $p"
	echo "php_ram_$p.draw LINE2"
	echo "php_ram_$p.info The current Memory Usage of PHP-FPM for pool '$p'."
    done
    exit 0
fi

for p in $PHP_POOLS; do
    echo -n "php_ram_$p.value "
    t=0
    for i in $(ps awx -o rss,cmd | grep "php-fpm: pool $p" | grep -v grep | grep -v phpfpm_memory | cut -d" " -f1); do
	t=$((t+i))
    done
    echo $((t*1024))
done
