#!/bin/sh
# -*- sh -*-

: <<=cut

=head1 NAME

phpfpm_average - Munin plugin to monitor the number of PHP5-FPM processes on the machine.

=head1 CONFIGURATION

You might need to specify connection parameters in the plugin
configuration to override the defaults. These are the defaults:

  [phpfpm_*]
    env.phpbin php-fpm
    env.phppool www

=head1 PARAMETERS:

 config (required)
 autoconf (optional - used by munin-config)

=over

=head1 LICENSE

Copyright TJ Stein 2010 http://constantshift.com

=head1 MAGICK MARKERS

  #%# family=manual
  #%# capabilities=autoconf

=cut

PHP_BIN=${phpbin-"php-fpm"}
# Get the list of all pools if non is specified in the config file
PHP_POOLS=${phppool-"$(ps -axo cmd | grep "php-fpm: pool" | grep -v grep | sort | uniq | cut -d" " -f 3)"}

if [ "$1" = "autoconf" ]; then
echo yes
exit 0
fi

if [ "$1" = "config" ]; then
echo 'graph_title PHP-FPM Processes'
echo 'graph_args --base 1000 -l 0 '
echo 'graph_category PHP'
echo 'graph_info This graph shows the number of PHP-FPM processes in the system.'
for p in $PHP_POOLS; do
    echo "graph_vlabel PHP-FPM Processes $p"
    echo "php_processes_$p.label PHP-FPM Processes: $p"
    echo "php_processes_$p.draw LINE2"
    echo "php_processes_$p.info The current number of PHP-FPM processes for pool '$p'."
done
exit 0
fi

for p in $PHP_POOLS; do
    echo -n "php_processes_$p.value "
    ps awwwux | grep "$PHP_BIN: pool $p" | grep -v grep | wc -l
done
